Section A: Data Structures & Control Structures

1.	Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [ ]:
numbers = [1,2,3,4,5]

numbers.append(6)
print("Append:", numbers)

numbers.extend([7,8,9])
print("Extend:", numbers)

numbers.insert(9,10)
print("Insert:", numbers)

numbers.remove(1)
print("Remove:", numbers)

numbers.pop(0)
print("Pop:", numbers)

print("Index of 4:", numbers.index(4))

print("Count of 3:", numbers.count(3))

numbers.sort()
print("Sort:", numbers)

numbers.reverse()
print("Reverse:", numbers)

numbers.clear()
print("Clear:", numbers)

Append: [1, 2, 3, 4, 5, 6]
Extend: [1, 2, 3, 4, 5, 6, 7, 8, 9]
Insert: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
Remove: [2, 3, 4, 5, 6, 7, 8, 9, 10]
Pop: [3, 4, 5, 6, 7, 8, 9, 10]
Index of 4: 1
Count of 3: 1
Sort: [3, 4, 5, 6, 7, 8, 9, 10]
Reverse: [10, 9, 8, 7, 6, 5, 4, 3]
Clear: []

2.	Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [ ]:
student_names = ('praveen','srinu','charan')
student_names[1] = 'vikki krishna'
print(student_names)

TypeError: 'tuple' object does not support item assignment

the tuple does not allow the change of elements,this property is known as immutability which also appears in the string

for changing the values in the tuple we can convert the tuple into a list using a list constructor

list()

3.	Create a set of integers with some duplicate values. Print the set and explain the output

In [ ]:
num = {1,2,3,1,2,1,3,4,5,6}
print(num)

{1, 2, 3, 4, 5, 6}

the set does does not allow the duplicates to be printed and it only prints the unique values

4.	Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [ ]:
details = {
    'name' : 'praveen',
    'age' : 21 ,
    'city' : 'andhra pradhesh'
}
details['age'] = 22
details['email'] = 'praveenguvvala325@gmail.com'
print(details)

{'name': 'praveen', 'age': 22, 'city': 'andhra pradhesh', 'email': 'praveenguvvala325@gmail.com'}

5.	 Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [ ]:
age = int(input('enter the age of yours :'))
if age >= 18 :
  print('you are eligible to vote')
else:
  print('you are not eligible to vote')

enter the age of yours :52
you are eligible to vote

6.	Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [ ]:
marks = int(input('enter your marks :'))
if marks >= 90 :
  print("your grade is 'A'")
elif marks >= 75 :
  print("your grade is 'B'")
elif marks >= 50 :
  print("your grade is 'C'")
else:
  print(" you failed in the exam")

enter your marks :55
your grade is 'C'

7.	Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [ ]:
number = int(input("Enter a number: "))
if number > 0:
    if number % 2 == 0:
        print(number, "is positive and even")
    else:
        print(number, "is positive but odd")
elif number == 0:
    print(number, "is zero")
else:
    print(number, "is negative")

Enter a number: 51
51 is positive but odd

Section B: Numpy

8.	Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [ ]:
import numpy as np

In [ ]:
num = np.array(5)

In [ ]:
num.ndim

0

In [ ]:
one_d_array = np.array([1,2,3,4,5])

In [ ]:
one_d_array

array([1, 2, 3, 4, 5])

In [ ]:
two_d_array = np.arange(10, 61, 10).reshape(2, 3)

In [ ]:
two_d_array

array([[10, 20, 30],
       [40, 50, 60]])

9.	Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [ ]:
arr = np.random.randint(0,100, size=(4,4))
arr

array([[ 6, 29, 54, 25],
       [57, 49,  8, 14],
       [22, 79, 41, 96],
       [96, 72, 70, 26]])

10.	Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [ ]:
import numpy as np
import pandas as pd

d_array = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
df = pd.DataFrame(d_array , columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

Section C: Exploring Pandas

11.	Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [2]:
import numpy as np
import pandas as pd

In [12]:
df = pd.DataFrame(

                  {
                      'name':['praveen','naveen','asif'],
                      'age' :[22,25,30],
                      'city':['tirupathi','hitech city','banglore'],
                      'salary':[10000,20000,30000]
                  }
)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   age     3 non-null      int64
 2   city    3 non-null      object
 3   salary  3 non-null      int64
dtypes: int64(2), object(2)
memory usage: 228.0+ bytes

In [14]:
df.describe()

             age   salary
count   3.000000      3.0
mean   25.666667  20000.0
std     4.041452  10000.0
min    22.000000  10000.0
25%    23.500000  15000.0
50%    25.000000  20000.0
75%    27.500000  25000.0
max    30.000000  30000.0

In [15]:
df[['name','city']]

      name         city
0  praveen    tirupathi
1   naveen  hitech city
2     asif     banglore

In [16]:
df.drop('city', axis=1, inplace=True)

In [17]:
print(df)

      name  age  salary
0  praveen   22   10000
1   naveen   25   20000
2     asif   30   30000

In [24]:
df.isnull().sum()

name      0
age       0
salary    0
dtype: int64

In [20]:
df['salary'] = df['salary'].fillna(df['salary'].mean())

the data set which i created has no null values but i did executed the command

In [21]:
df[['salary']]

   salary
0   10000
1   20000
2   30000

In [25]:
df.duplicated().sum()

np.int64(0)

there is no duplicates in the data set i created but i will execute the command

In [26]:
df.drop_duplicates()

      name  age  salary
0  praveen   22   10000
1   naveen   25   20000
2     asif   30   30000